# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-nCLuJk7y4PdSvzREeZSTmtBHWUMotO
"""

import streamlit as st
from google import genai

# Initialize the official Gemini Client using the provided API key.
gemini_api_key = st.secrets["gemini_api_key"]
gmn_client = genai.Client(api_key=gemini_api_key)

def generate_gemini_answer(prompt, mode="landlord"):
    """
    prompt: The raw station data (Traffic, Max Card, etc.)
    mode: "landlord" for Asset Optimizer view, "retail" for Customer Demand view
    """
    
    # Configuration for your two specific AI personas
    PERSONA_PROMPTS = {
        "landlord": (
            "คุณคือ Leasing Strategy Manager และ Asset Optimizer สำหรับธุรกิจ Retail ในสถานีบริการน้ำมัน "
            "หน้าที่ของคุณคือวิเคราะห์ข้อมูลเพื่อแนะนำ 'ผู้เช่าประเภทใด' ที่จะสร้าง Rental Yield และ Synergy สูงสุด "
            "ภารกิจ: วิเคราะห์ Optimal Tenant Mix เน้นรายได้ระยะยาวและการใช้พื้นที่คุ้มค่า (Yield per Sq.m.)\n\n"
            "ข้อมูลนำเข้าที่ต้องใช้: Station Dynamics, Customer Insights, Site Constraints, Market Gap\n\n"
            "รูปแบบการตอบกลับ: 1. Top 3 Recommended Tenant Types, 2. Landlord Value Proposition, "
            "3. Site Compatibility Analysis, 4. Risk & Opportunity Score\n\n"
        ),
        "retail": (
            "คุณคือผู้เชี่ยวชาญด้าน Business Intelligence และ Retail Strategy ที่เชี่ยวชาญการวิเคราะห์ทำเลสถานี PTG "
            "เพื่อจับคู่ความต้องการของผู้บริโภคกับประเภทร้านค้าที่เหมาะสม (Matching Engine)\n\n"
            "ภารกิจ: สร้าง Recommended Retail Concepts โดยเรียงลำดับตามความเหมาะสม พร้อมเหตุผลและตัวเลขคาดการณ์\n\n"
            "รูปแบบการตอบกลับ: 1. Top 3 Recommended Concepts, 2. Strategic Rationale, "
            "3. Predicted Metrics (Demand Score, Target Group, Potential Revenue)\n\n"
        )
    }

    try:
        # Select the correct persona based on the mode
        system_context = PERSONA_PROMPTS.get(mode, PERSONA_PROMPTS["landlord"])
        
        # Combine the System Instruction with the User's station data
        full_input = f"{system_context}\nStation Data Input:\n{prompt}"

        # Call the Gemini 2.5 Flash Lite model
        response = gmn_client.models.generate_content(
            model='gemini-2.5-flash-lite',
            contents=full_input
        )
        return response.text

    except Exception as e:
        # Gracefully handle and display any errors
        return f"Error during Gemini text generation: {e}"

# Initialize an empty list to store the conversation history
if "messages" not in st.session_state:
    st.session_state.messages = []

st.title('Gemini Chat Test')

# Loop through all messages stored in the session state and display them
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])


# st.chat_input displays the chat box at the bottom of the screen.
if prompt := st.chat_input("Message to Gemini..."):
    # 1. Save the user's message to the session state history
    st.session_state.messages.append({"role": "user", "content": prompt})

    # 2. Display the user's message immediately in the UI
    with st.chat_message("user"):
        st.markdown(prompt)

    # 3. Call the helper function to get the AI's response and display it
    with st.chat_message("assistant"):
        response = generate_gemini_answer(prompt)
        st.markdown(response)

    # 4. Save the AI's response to the session state history
    st.session_state.messages.append({"role": "assistant", "content": response})
